sonar.projectKey=SiyovushShuk_python-project-83
sonar.organization=siyovushshuk

sonar.python.coverage.reportPaths=coverage.xml

sonar.sources=page_analyzer
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.coverage.exclusions=tests/**


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=python-project-83
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
